config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :clients, only: %i[index show]
  resources :attachments

  resources :users, only: %i[] do
    member do
      patch 'update_password'
      get 'edit_password'
    end
  end

  namespace :admin do
    resources :clients
    resources :users do
      member do
        patch :change_user_status, to: 'users#enable_disable_user'
      end
    end
    resources :projects, controller: '/projects' do
      resources :payments, controller: '/payments'
      resources :comments, controller: '/comments'
      resources :time_logs, controller: '/time_logs'
    end
  end

  namespace :manager do
    resources :clients
    resources :projects, controller: '/projects' do
      resources :payments, controller: '/payments'
      resources :comments, controller: '/comments'
      resources :time_logs, controller: '/time_logs'
    end
  end

  namespace :developer do
    resources :projects, only: %i[index show], controller: '/projects' do
      resources :comments, controller: '/comments'
      resources :time_logs, controller: '/time_logs'
    end
  end

  root 'dashboard#index'

  namespace :api do
    namespace :v1 do
      post '/auth/login', to: 'authentication#login'
      resources :users
      resources :clients
      resources :projects do
        resources :payments
        resources :comments
        resources :time_logs
        resources :attachments
      end
    end
    get '/*a', to: 'api#not_found'
  end

  get '*no_route_matches', to: redirect('404')
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  paginates_per 5

  has_many :projects

  validates :name, :email, :address, presence: true
  validates :name, length: { in: 5..15 }

  pg_search_scope :search, against: [:name]
end

app/controllers/admin/clients_controller.rb
# frozen_string_literal: true

class Admin::ClientsController < ClientsController
  def new
    @client = Client.new
    authorize @client, policy_class: Admin::ClientPolicy
  end

  def edit
    authorize @client, policy_class: Admin::ClientPolicy
  end

  def create
    @client = Client.new(client_params)
    authorize @client, policy_class: Admin::ClientPolicy

    if @client.save
      redirect_to @client, notice: 'Client was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize @client, policy_class: Admin::ClientPolicy

    if @client.update(client_params)
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @client, policy_class: Admin::ClientPolicy

    @client.destroy
    redirect_to clients_path, notice: 'Client was successfully destroyed.'
  end
end

app/controllers/api/v1/clients_controller.rb
# frozen_string_literal: true

class Api::V1::ClientsController < Api::ApiController
  before_action :user_authentication, only: %i[create update destroy]
  before_action :set_client, only: %i[show update destroy]

  def index
    @clients = Client.all
    success_response(@clients)
  end

  def show
    success_response(@client)
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      success_response(@client, :created)
    else
      failure_response(@client.errors)
    end
  end

  def update
    if @client.update(client_params)
      success_response(@client, :updated)
    else
      failure_response(@client.errors)
    end
  end

  def destroy
    if @client.destroy
      success_response(@client, :deleted)
    else
      failure_response(@client.errors)
    end
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:name, :email, :address)
  end
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < ApplicationController
  before_action :set_client, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      @clients = Client.all.search(params[:query])
    else
      @clients = Client.all
    end
    @clients = @clients.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @projects = @client.projects
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:name, :email, :address)
  end
end

app/controllers/manager/clients_controller.rb
# frozen_string_literal: true

class Manager::ClientsController < ClientsController
  def new
    @client = Client.new
    authorize @client, policy_class: Manager::ClientPolicy
  end

  def edit
    authorize @client, policy_class: Manager::ClientPolicy
  end

  def create
    @client = Client.new(client_params)
    authorize @client, policy_class: Manager::ClientPolicy

    if @client.save
      redirect_to @client, notice: 'Client was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize @client, policy_class: Manager::ClientPolicy

    if @client.update(client_params)
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @client, policy_class: Manager::ClientPolicy

    @client.destroy
    redirect_to clients_path, notice: 'Client was successfully destroyed.'
  end
end

app/views/manager/clients/_form.html.erb
<%= form_for @client, url: yield(:path) do |form| %>
  <%= render 'shared/errors', object: @client %>

  <div class='form-group col-md-6'>
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class='form-group col-md-6'>
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control', required: true %>
  </div>

  <div class='form-group col-md-6'>
    <%= form.label :address %>
    <%= form.text_field :address, class: 'form-control', required: true %>
  </div>

  <div class='form-group col-md-6'>
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/manager/clients/_manager_header.html.erb
<%= link_to fa_icon('arrow-left'), manager_clients_path, class: 'btn btn-info', title: 'Back' %>

app/views/manager/clients/edit.html.erb
<div class='container'>
  <% content_for :title, 'Edit Client Profile' %>
  <% provide(:path, manager_client_path) %>

  <div class='form-group margin_left_right_15'>
    <%= render 'manager_header' %>
    <span><b>Edit Client</b></span>
  </div>

  <%= render 'form', client: @client %>
</div>

app/views/manager/clients/new.html.erb
<div class='container'>
  <% content_for :title, 'Create Client' %>
  <% provide(:path, manager_clients_path) %>

  <div class='form-group margin_left_right_15'>
    <%= render 'manager_header' %>
    <span><b>New Client</b></span>
  </div>

  <%= render 'form', client: @client %>
</div>