config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :clients, only: %i[index show]
  resources :attachments

  resources :users, only: %i[] do
    member do
      patch 'update_password'
      get 'edit_password'
    end
  end

  namespace :admin do
    resources :clients
    resources :users do
      member do
        patch :change_user_status, to: 'users#enable_disable_user'
      end
    end
    resources :projects, controller: '/projects' do
      resources :payments, controller: '/payments'
      resources :comments, controller: '/comments'
      resources :time_logs, controller: '/time_logs'
    end
  end

  namespace :manager do
    resources :clients
    resources :projects, controller: '/projects' do
      resources :payments, controller: '/payments'
      resources :comments, controller: '/comments'
      resources :time_logs, controller: '/time_logs'
    end
  end

  namespace :developer do
    resources :projects, only: %i[index show], controller: '/projects' do
      resources :comments, controller: '/comments'
      resources :time_logs, controller: '/time_logs'
    end
  end

  root 'dashboard#index'

  namespace :api do
    namespace :v1 do
      post '/auth/login', to: 'authentication#login'
      resources :users
      resources :clients
      resources :projects do
        resources :payments
        resources :comments
        resources :time_logs
        resources :attachments
      end
    end
    get '/*a', to: 'api#not_found'
  end

  get '*no_route_matches', to: redirect('404')
end

app/models/attachment.rb
# frozen_string_literal: true

class Attachment < ApplicationRecord
  mount_uploader :filename, AttachmentUploader
  paginates_per 5

  belongs_to :attachable, polymorphic: true
end

app/controllers/api/v1/attachments_controller.rb
# frozen_string_literal: true

class Api::V1::AttachmentsController < Api::ApiController
  def index
    @attachments = Attachment.all
    success_response(@attachments, :ok)
  end

  def show
    @project = Project.find(params[:project_id])
    @attachment = @project.attachments.find(params[:id])
    success_response(@attachment, :ok)
  end
end

app/controllers/attachments_controller.rb
# frozen_string_literal: true

class AttachmentsController < ApplicationController
  before_action :set_attachment, only: %i[edit update destroy]

  def new
    @attachment = Attachment.new
  end

  def edit; end

  def create
    @attachment = Attachment.new(attachment_params)
    @attachment.save
  end

  def update
    @attachment.update(attachment_params)
  end

  def destroy
    @success = @attachment.destroy
  end

  private

  def set_attachment
    @attachment = Attachment.find(params[:id])
  end

  def attachment_params
    params.require(:attachment).permit(:filename, :attachable_id, :attachable_type)
  end
end

app/views/attachments/_attachment_row.html.erb
<tr id= <%= "attachable_row_#{attachment.id}" %>>
  <td>
    <a href='<%= attachment.filename %>' target='_blank'> <%= attachment.filename %></a>
  </td>
  <td>
    <div>
      <a href='<%= attachment.filename %>' download=''><i class="fa fa-download"></i></a>
      <%= link_to fa_icon('trash'), attachment_path(attachment), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'delete color-red col-md-6', title: 'Delete' %>
    </div>
  </td>
</tr>

app/views/attachments/_attachment_table.html.erb
<div id='attachment_details' class='shadow p-3 mb-5 bg-white rounded'>

  <table class='table table-bordered' id='attachments'>
    <thead>
      <tr>
        <th>File Name</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody id='time_log_row'>
      <%= render partial: 'attachments/attachment_row', collection: @attachments, as: :attachment %>
    </tbody>
  </table>

  <div class='attachment-paginator'>
    <%= paginate @attachments, remote: true, param_name: :attachment_page, params: { controller: :projects, action: :show } %>
  </div>
</div>

app/views/attachments/_form.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="staticBackdropLabel">Please Enter The Payment</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class='errors-div'></div>

<div class="modal-body">
  <%= form_for @attachment, remote: true do |f| %>
    <div class="form-group">
      <div class="form-label-group">
        <%= f.label :filename %>
        <%= f.file_field :filename %>
      </div>
      <%= f.hidden_field :attachable_id, value: attachable_id %>
      <%= f.hidden_field :attachable_type, value: attachable_type  %>

    <div class='mb-5 mt-3'>
      <%= f.submit 'Save Photo', class: "btn btn-primary btn-block" %>
    </div>
  <% end %>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>

app/views/attachments/create.js.erb
<% if @attachment.save %>
  $('#myModal').modal('hide');
  $('table#attachments tbody').append("<%= j render 'attachment_row', attachment: @attachment %>");
<% else %>
  $('.errors-div').replaceWith("<%= j render 'shared/errors', object: @attachment %>");
<% end %>

app/views/attachments/destroy.js.erb
<% if @success %>
$('.delete').bind('ajax:success', function(){
  $(this).closest('tr').fadeOut();
});
<% else %>
  $('.errors-div').replaceWith("<%= j render 'shared/errors', object: @attachment %>");
<% end %>

app/views/attachments/edit.js.erb
$(".modal").find(".modal-content").html("<%= j (render 'form', attachment: @attachment) %>");
$(".modal").modal();

app/views/attachments/new.js.erb
$(".modal").find(".modal-content").html("<%= j (render 'form', attachable_id: params[:attachable_id],attachable_type: params[:attachable_type] ) %>");
$(".modal").modal();

app/views/attachments/update.js.erb
<% if @attachment.errors.any? %>
  $('.errors-div').replaceWith("<%= j render 'shared/errors', object: @attachment %>");
<% else %>
  $('#myModal').modal('hide');
  $('div user-photo').replaceWith("<%= image_tag (current_user.attachment.filename.url if current_user.attachment), class: 'rounded' %>");
<% end %>