config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :clients, only: %i[index show]
  resources :attachments

  resources :users, only: %i[] do
    member do
      patch 'update_password'
      get 'edit_password'
    end
  end

  namespace :admin do
    resources :clients
    resources :users do
      member do
        patch :change_user_status, to: 'users#enable_disable_user'
      end
    end
    resources :projects, controller: '/projects' do
      resources :payments, controller: '/payments'
      resources :comments, controller: '/comments'
      resources :time_logs, controller: '/time_logs'
    end
  end

  namespace :manager do
    resources :clients
    resources :projects, controller: '/projects' do
      resources :payments, controller: '/payments'
      resources :comments, controller: '/comments'
      resources :time_logs, controller: '/time_logs'
    end
  end

  namespace :developer do
    resources :projects, only: %i[index show], controller: '/projects' do
      resources :comments, controller: '/comments'
      resources :time_logs, controller: '/time_logs'
    end
  end

  root 'dashboard#index'

  namespace :api do
    namespace :v1 do
      post '/auth/login', to: 'authentication#login'
      resources :users
      resources :clients
      resources :projects do
        resources :payments
        resources :comments
        resources :time_logs
        resources :attachments
      end
    end
    get '/*a', to: 'api#not_found'
  end

  get '*no_route_matches', to: redirect('404')
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  paginates_per 5

  has_and_belongs_to_many :resources, class_name: 'User', dependent: :destroy

  has_many :time_logs, dependent: :destroy
  has_many :payments, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy

  belongs_to :client
  belongs_to :manager, class_name: 'User'
  belongs_to :created_by, class_name: 'User'

  validates :name, :details, presence: true

  pg_search_scope :search, against: [:name]

  def self.fetch_current_user_projects(user)
    if user.admin?
      all
    elsif user.manager?
      where(manager: user).or(Project.where(created_by: user))
    elsif user.developer?
      user.projects
    end
  end

  def self.top_projects
    Project.order(total_payments: :desc).limit(5)
  end

  def self.bottom_projects
    Project.order(total_payments: :asc).limit(5)
  end
end

app/controllers/api/v1/projects_controller.rb
# frozen_string_literal: true

class Api::V1::ProjectsController < Api::ApiController
  before_action :user_authentication, only: %i[create update destroy]
  before_action :set_project, only: %i[show update destroy]

  def index
    @projects = Project.fetch_current_user_projects(current_user)
    authorize @projects, policy_class: ProjectPolicy
    success_response(@projects)
  end

  def show
    authorize @project, policy_class: ProjectPolicy
    success_response(@project)
  end

  def create
    @project = Project.new(project_params)
    authorize @project, policy_class: ProjectPolicy

    if @project.save
      success_response(@project, :created)
    else
      failure_response(@project.errors)
    end
  end

  def update
    authorize @project, policy_class: ProjectPolicy

    if @project.update(project_params)
      success_response(@project, :updated)
    else
      failure_response(@project.errors)
    end
  end

  def destroy
    authorize @project, policy_class: ProjectPolicy

    if @project.destroy
      success_response(@project, :deleted)
    else
      failure_response(@project.errors)
    end
  end

  private

  def set_project
    @project = Project.fetch_current_user_projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :details, :total_payments, :hours_logged, :created_by_id, :manager_id, :client_id)
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  include ProjectHelper

  before_action :set_project, only: %i[show edit update destroy]
  before_action :set_clients, :set_managers, only: %i[new edit]

  def index
    if params[:query].present?
      @projects = Project.fetch_current_user_projects(current_user).search(params[:query])
    else
      @projects = Project.fetch_current_user_projects(current_user)
    end
    @projects = @projects.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @project = Project.new
    authorize @project
  end

  def show
    authorize @project
    @payments = @project.payments.page(params[:payment_page])
    @time_logs = @project.time_logs.page(params[:time_log_page])
    @attachments = @project.attachments.page(params[:attachment_page])
    @comments = @project.comments

    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    @project.created_by = current_user
    authorize @project

    if @project.save!
      redirect_to generic_path_method('show', 'project', @project), notice: 'Project created successfully.'
    else
      render :new
    end
  end

  def update
    authorize @project

    if @project.update(project_params)
      redirect_to generic_path_method('show', 'project', @project), notice: 'Project successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @project

    @project.destroy
    redirect_to generic_path_method('index', 'project', @projects), notice: 'Project successfully deleted.'
  end

  private

  def set_managers
    @managers = User.managers.order(:name)
  end

  def set_clients
    @clients = Client.order(:name)
  end

  def set_project
    @project = Project.fetch_current_user_projects(current_user).find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :details, :client_id, :manager_id, resource_ids: [])
  end
end

app/helpers/project_helper.rb
# frozen_string_literal: true

module ProjectHelper
  def project_total_payments(project)
    project.payments.to_a.sum(&:amount)
  end

  def project_hours_logged(project)
    time = 0
    project.time_logs.each do |time_log|
      time += ((time_log.end_time - time_log.start_time) / 60 / 60).to_i
    end
    time
  end
end

app/views/projects/_form.html.erb
<%= form_for @project, url: yield(:path), remote: true do |form| %>
  <div class='form-group col-md-6'>
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class='form-group col-md-6'>
    <%= form.label :details %>
    <%= form.text_field :details, class: 'form-control', required: true %>
  </div>

  <div class='form-group col-md-6'>
    <%= form.label :client %>
    <%= form.select :client_id, options_from_collection_for_select(@clients, :id, :name, selected: project.client_id), {}, class: 'form-control' %>
  </div>

  <div class='form-group col-md-6'>
    <%= form.label :manager %>
    <%= form.select :manager_id, options_from_collection_for_select(@managers, :id, :name, selected: project.manager_id), {}, class: 'form-control' %>
  </div>


  <div class='form-group col-md-6'>
    <%= form.label :resources %>
    <%= form.select :resource_ids, User.where(role: 'developer').map { |e| [e.name, e.id] }, { include_blank: true, include_hidden: false }, class: 'chosen-select form-control', multiple: true, data: { placeholder: 'Select' } %>
  </div>

  <%= form.hidden_field :created_by_id, value: current_user.id %>

  <div class='form-group col-md-6'>
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>


<script>
  $('.chosen-select').chosen();
</script>

app/views/projects/_payment_modal.html.erb
<div class="modal fade" id="myModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/projects/_project_header.html.erb
<%= link_to fa_icon('arrow-left'), projects_path, class: 'btn btn-info', title: 'Back' %>

app/views/projects/_projects_table.html.erb
<div>
  <table class='table table-hover'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% projects.each do |project| %>
        <tr>
          <td><%= project.name %></td>
          <td>
            <%= link_to fa_icon('eye'), generic_path_method('show', 'project', project), class: 'col-md-6', title: 'See Profile' %>
            <% if current_user.manager? || current_user.admin? %>
              <%= link_to fa_icon('pencil-square-o'), generic_path_method('edit', 'project', project), class: 'col-md-6', title: 'Edit Profile' %>
              <%= link_to fa_icon('trash'), generic_path_method('destroy', 'project', project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'col-md-6', title: 'Delete' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate projects %>
</div>

app/views/projects/edit.html.erb
<div class='container'>
<% content_for :title, 'Edit Project Profile' %>
<% provide(:path, generic_path_method('update', 'project', @project)) %>

  <div class='form-group margin_left_right_15'>

    <span><b>Edit Project</b></span>
  </div>

  <%= render 'form', project: @project, clients: @clients, manager: @manager %>
</div>

app/views/projects/index.html.erb
<% content_for :title, 'Projects' %>

<div class='container'>
  <div class='row'>
    <% if current_user.admin? || current_user.manager? %>
      <div class='form-group col-md-6'>
        <%= link_to fa_icon('user-plus'), generic_path_method('new', 'project'), class: 'btn btn-primary', title: 'Create Project' %>
      </div>
    <% end %>
  </div>

  <div class='form-group float-right'>
    <%= form_tag(generic_path_method('index', 'project'), method: :get, remote: true) do %>
      <div class='input-group active-cyan-4 mb-4'>
        <%= search_field_tag :query, params[:query], placeholder: 'Search', class: 'form-control' %>
        <div class='input-group-btn ml-3'>
          <%= button_tag "", class: 'btn btn-info fa fa-search' %>
        </div>
      </div>
    <% end %>
  </div>


  <h1>Projects</h1>

  <div class='all_projects'>
    <%= render 'projects_table', projects: @projects %>
  </div>
</div>

app/views/projects/index.js.erb
$(".all_projects").find('.table').replaceWith("<%= j (render 'projects_table', projects: @projects) %>");

app/views/projects/new.html.erb
<div class='container'>
<% content_for :title, 'Create Project' %>
<% provide(:path, generic_path_method('create', 'project', @project)) %>

  <div class='form-group margin_left_right_15'>

    <span><b>New Project</b></span>
  </div>

  <%= render 'form', project: @project, clients: @clients %>
</div>

app/views/projects/search.html.erb
<div class='container'>

<h2>Search Result</h2>

  <table class='table table-hover'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @results.each do |project| %>
        <tr>
          <td><%= project.name %></td>
          <td>
            <%= link_to fa_icon('eye'), generic_path_method('show', 'project', project), class: 'col-md-6', title: 'See Profile' %>
            <% if current_user.manager? || current_user.admin? %>
              <%= link_to fa_icon('pencil-square-o'), generic_path_method('edit', 'project', project), class: 'col-md-6', title: 'Edit Profile' %>
              <%= link_to fa_icon('trash'), generic_path_method('destroy', 'project', project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'col-md-6', title: 'Delete' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/projects/show.html.erb
<% content_for :title, 'Project Details' %>

<div class='container'>
  <div>
    <h2 class='d-inline'>Project Details</h2>
    <% if current_user.admin? || current_user.manager? %>
      <%= link_to fa_icon('pencil-square-o'), generic_path_method('edit', 'project', @project), class: 'btn btn-info float-right', title: 'Edit Project' %>
    <% end %>
    <hr class='my-hr'>

    <div class='shadow p-3 mb-5 bg-white rounded'>
      <p><span><b>Name: </b></span><%= capitalize(@project.name) %></p>
      <p><span><b>Details: </b></span><%= capitalize(@project.details) %></p>
      <p><span><b>Manager: </b></span><%= capitalize(@project.manager.name) if @project.manager %></p>
      <p><span><b>Client: </b></span><%= capitalize(@project.client.name) if @project.client %></p>
      <p>
        <span><b>Resources: </b>
          <% @project.resources.each do |resource| %>
            <%= capitalize(resource.name) if resource %>
          <% end %>
        </span>
      </p>
      <% if current_user.admin? || current_user.manager? %>
        <p>
          <span><b>Total Payments: </b></span>
          <span class='project_total_payments_class'><%= project_total_payments(@project) %></span> $
        </p>
      <% end %>
      <p>
        <span><b>Total Hours Logged: </b></span>
        <span class='project_hours_logged_class'><%= project_hours_logged(@project) %></span> Hours
      </p>
    </div>
  </div>

  <div>
    <% if current_user.manager? || current_user.admin? %>
      <h3 class='d-inline'>Payments</h3>
      <%= link_to fa_icon('plus'), generic_path_method('new', 'project_payment', @project), remote: true, class: 'btn btn-primary' %>
      <div class='mb-5 mt-3'>
        <%= render 'payments/payment_table', payments: @payments %>
      </div>
    <% end %>
  </div>

  <div>
    <h3 class='d-inline'>Time Logs</h3>
    <%= link_to fa_icon('plus'), generic_path_method('new', 'project_time_log', @project), remote: true, class: 'btn btn-primary' %>
    <div class='mb-5 mt-3'>
      <%= render 'time_logs/time_log_table', time_logs: @time_logs %>
    </div>
  </div>

  <div>
    <h3 class='d-inline'>Attachments</h3>
    <%= link_to fa_icon('plus'), new_attachment_path(attachable_id: @project.id, attachable_type: @project.class.to_s), remote: true, class: 'btn btn-primary' %>
    <div class='mb-5 mt-3'>
      <%= render 'attachments/attachment_table', attachments: @attachments %>
    </div>
  </div>

  <div>
    <h3>Comments</h3>
    <div class='comment_box_size shadow p-3 mb-5 bg-white rounded'>
      <%= render 'comments/all_comments', comments: @comments %>
    </div>
      <%= render 'comments/new_form', project: @project %>
  </div>
</div>

<%= render 'shared/modal' %>

app/views/projects/show.js.erb
$("#payment_row").html("<%= j render partial: 'payments/payment_row', collection: @payments, as: :payment %>");
$(".payment-paginator").html("<%= j paginate @payments, param_name: 'payment_page', remote: true %>");

$("#time_log_row").html("<%= j render partial: 'time_logs/time_log_row', collection: @time_logs, as: :time_log %>");
$(".time_log-paginator").html("<%= j paginate @time_logs, param_name: 'time_log_page', remote: true %>");

$("#attachment_row").html("<%= j render partial: 'attachments/attachment_row', collection: @attachments, as: :attachment %>");
$(".attachment-paginator").html("<%= j paginate @attachments, param_name: 'attachment_page', remote: true %>");