config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :clients, only: %i[index show]
  resources :attachments

  resources :users, only: %i[] do
    member do
      patch 'update_password'
      get 'edit_password'
    end
  end

  namespace :admin do
    resources :clients
    resources :users do
      member do
        patch :change_user_status, to: 'users#enable_disable_user'
      end
    end
    resources :projects, controller: '/projects' do
      resources :payments, controller: '/payments'
      resources :comments, controller: '/comments'
      resources :time_logs, controller: '/time_logs'
    end
  end

  namespace :manager do
    resources :clients
    resources :projects, controller: '/projects' do
      resources :payments, controller: '/payments'
      resources :comments, controller: '/comments'
      resources :time_logs, controller: '/time_logs'
    end
  end

  namespace :developer do
    resources :projects, only: %i[index show], controller: '/projects' do
      resources :comments, controller: '/comments'
      resources :time_logs, controller: '/time_logs'
    end
  end

  root 'dashboard#index'

  namespace :api do
    namespace :v1 do
      post '/auth/login', to: 'authentication#login'
      resources :users
      resources :clients
      resources :projects do
        resources :payments
        resources :comments
        resources :time_logs
        resources :attachments
      end
    end
    get '/*a', to: 'api#not_found'
  end

  get '*no_route_matches', to: redirect('404')
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  paginates_per 5

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  enum role: %i[developer admin manager]
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/

  after_initialize :set_default_role, if: :new_record?

  has_and_belongs_to_many :projects

  has_many :time_logs
  has_one :attachment, as: :attachable
  has_many :comments, foreign_key: :commenter_id

  validates :name, :address, :cnic, :phone_number, presence: true
  validates :name, length: { in: 5..15 }
  validates :cnic, length: { is: 13 }
  validates :address, length: { maximum: 100 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

  scope :developers, -> { where role: 'developer' }
  scope :managers, -> { where role: 'manager' }
  scope :admins, -> { where role: 'admin' }
  scope :except_current_user, ->(user) { where.not(id: user) }

  pg_search_scope :search, against: [:name]

  def set_default_role
    self.role ||= :developer
  end

  def active_for_authentication?
    super && enable?
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < UsersController
  before_action :set_admin, only: %i[enable_disable_user show edit update destroy]

  def index
    if params[:query].present?
      @users = User.except_current_user(current_user).search(params[:query])
    else
      @users = User.except_current_user(current_user)
    end
    @users = @users.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
    authorize User
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new(admin_user_params)
    authorize @user

    if @user.save
      redirect_to admin_users_path, notice: 'User successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @admin.update(admin_user_params)
      redirect_to admin_users_path, notice: 'User profile successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @admin.destroy
    redirect_to admin_users_path, notice: 'User successfully deleted.'
  end

  def enable_disable_user
    @admin.toggle!(:enable)
    redirect_to admin_users_path, notice: 'User status successfully updated.'
  end

  private

  def set_admin
    @admin = User.find(params[:id])
    authorize @admin
  end

  def admin_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :address, :cnic, :phone_number, :role, :enable)
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

class Api::V1::UsersController < Api::ApiController
  before_action :user_authentication_is_admin
  before_action :set_user, only: %i[show update destroy]

  def index
    @users = User.all
    authorize User, policy_class: UserPolicy
    success_response(@users)
  end

  def show
    authorize @user, policy_class: UserPolicy
    success_response(@user)
  end

  def create
    @user = User.new(user_params)
    authorize @user, policy_class: UserPolicy

    if @user.save
      success_response(@user, :created)
    else
      failure_response(@user.errors)
    end
  end

  def update
    authorize @user, policy_class: UserPolicy

    if @user.update(user_params)
      success_response(@user, :updated)
    else
      failure_response(@user.errors)
    end
  end

  def destroy
    authorize @user, policy_class: UserPolicy

    if @user.destroy
      success_response(@user, :deleted)
    else
      failure_response(@user.errors)
    end
  end

  private

  def find_user
    @user = User.find_by_email!(params[:email])
  rescue ActiveRecord::RecordNotFound
    render json: { errors: 'User not found' }, status: :not_found
  end

  def user_authentication_is_admin
    raise Pundit::NotAuthorizedError unless current_user.admin?
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:users).permit(:name, :email, :password, :password_confirmation, :address, :cnic, :phone_number, :role, :enable)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update show edit_password update_password]

  def edit_password; end

  def update_password
    if current_user.update(user_params)
      bypass_sign_in(current_user)
      current_user.save(validate: false)
      redirect_to users_home_path
    else
      render :edit_password
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
  def roles_helper
    roles = User.roles.keys.map { |role| [role.titleize, role] }
  end
end

app/views/admin/users/_users_table.html.erb
<table class='table table-hover table-bordered'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.role.capitalize %></td>
        <td>
          <% if !user.admin? %>
            <% if user.enable? %>
              <%= link_to fa_icon('lock'), change_user_status_admin_user_path(user.id), method: :patch, data: { confirm: 'Are you sure?' }, class: 'col-md-6', title: 'Disable User' %>
            <% else %>
              <%= link_to fa_icon('unlock'), change_user_status_admin_user_path(user.id), method: :patch, data: { confirm: 'Are you sure?' }, class: 'col-md-6', title: 'Enable User' %>
            <% end %>
            <%= link_to fa_icon('eye'), admin_user_path(user), class: 'col-md-6', title: 'See Profile' %>
            <%= link_to fa_icon('pencil-square-o'), edit_admin_user_path(user), class: 'col-md-6', title: 'Edit Profile' %>
            <%= link_to fa_icon('trash'), admin_user_url(user.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'col-md-6', title: 'Delete' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/admin/users/edit.html.erb
<% content_for :title, 'Edit User Profile' %>

<div class='container'>
  <div class='form-group margin_left_right_15'>
    <%= link_to fa_icon('arrow-left'), admin_users_path, class: 'btn btn-info', title: 'Back' %>
    <span><b>Edit User</b></span>
  </div>

  <%= form_for @user, url: admin_user_path(@user) do |form| %>
    <div class='form-group col-md-6'>
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control', required: true %>
    </div>

    <div class='form-group col-md-6'>
      <%= form.label :email %>
      <%= form.text_field :email, class: 'form-control', required: true %>
    </div>

    <div class='form-group col-md-6'>
      <%= form.label :address %>
      <%= form.text_field :address, class: 'form-control', required: true %>
    </div>

    <div class='form-group col-md-6'>
      <%= form.label :cnic %>
      <%= form.text_field :cnic, class: 'form-control' %>
    </div>

    <div class='form-group col-md-6'>
      <%= form.label :phone_number %>
      <%= form.text_field :phone_number, class: 'form-control' %>
    </div>

    <div class='form-group col-md-6'>
      <%= form.label :role %>
      <%= form.select :role, roles_helper, {}, class: 'form-control' %>
    </div>

    <div class='form-group col-md-6'>
      <%= form.submit 'Update Profile', class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<% content_for :title, 'Users' %>

<div class='container'>
  <div class='row'>
    <div class='form-group col-md-6'>
      <%= link_to new_admin_user_path, class: 'btn btn-primary' do %>
        <% fa_icon 'user-plus', title: 'Create User' %>
      <% end %>
    </div>
  </div>

  <div class='form-group float-right'>
    <%= form_tag(admin_users_path, method: :get, remote: true) do %>
      <div class='input-group active-cyan-4 mb-4'>
        <%= search_field_tag :query, params[:query], placeholder: 'Search', class: 'form-control' %>
        <div class='input-group-btn ml-3'>
          <%= button_tag "", class: 'btn btn-info fa fa-search' %>
        </div>
      </div>
    <% end %>
  </div>

  <h1>Users</h1>
  <div class='all_users'>
    <%= render 'users_table', users: @users %>
  </div>
</div>

app/views/admin/users/index.js.erb
$(".all_users").find('.table').replaceWith("<%= j (render 'users_table', users: @users) %>");

app/views/admin/users/new.html.erb
<% content_for :title, 'Create User' %>

<div class='container'>
  <div class='form-group margin_left_right_15'>
    <%= link_to fa_icon('arrow-left'), admin_users_path, class: 'btn btn-info', title: 'Back' %>
    <span><b>New User</b></span>
  </div>

  <%= render 'shared/errors', object: @user %>

  <%= form_for @user, url: admin_users_path do |form| %>
    <div class='form-group col-md-6'>
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control', required: true %>
    </div>

    <div class='form-group col-md-6'>
      <%= form.label :email %>
      <%= form.text_field :email, class: 'form-control', required: true %>
    </div>

    <div class='form-group col-md-6'>
      <%= form.label :password %>
      <%= form.password_field :password, class: 'form-control', required: true %>
    </div>

    <div class='form-group col-md-6'>
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class: 'form-control', required: true %>
    </div>

    <div class='form-group col-md-6'>
      <%= form.label :address %>
      <%= form.text_field :address, class: 'form-control', required: true %>
    </div>

    <div class='form-group col-md-6'>
      <%= form.label :cnic %>
      <%= form.text_field :cnic, class: 'form-control' %>
    </div>

    <div class='form-group col-md-6'>
      <%= form.label :phone_number %>
      <%= form.text_field :phone_number, class: 'form-control' %>
    </div>

    <div class='form-group col-md-6'>
      <%= form.label :role %>
      <%= form.select(:role, roles_helper, {} , class: 'form-control') %>
    </div>

    <div class='form-group col-md-6'>
      <%= form.submit class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<% content_for :title, 'User Profile' %>

<div class='container'>
  <%= link_to fa_icon('arrow-left'), admin_users_path, class: 'btn btn-info' %>
  <%= link_to fa_icon('pencil-square-o'), edit_admin_user_path, class: 'btn btn-info' %>
  <h3>Details:</h3>
    <div class='shadow p-3 mb-5 mt-2 bg-white rounded'>
      <p><span><b>Name: </b></span><%= capitalize(@user.name) %></p>
      <p><span><b>Email: </b></span><%= capitalize(@user.email) %></p>
      <p><span><b>Role: </b></span><%= capitalize(@user.role) %></p>
      <p><span><b>Address: </b></span><%= capitalize(@user.address) %></p>
      <p><span><b>Cnic: </b></span><%= capitalize(@user.cnic) %></p>
      <p><span><b>Phone Number: </b></span><%= capitalize(@user.phone_number) %></p>
    </div>
</div>